spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    urr: jdbc:mysql://localhost:3306/chenhai
    username: root
    password: 123456

server:
  port: 8080
